name: 'Setup Node'

inputs:
  node-version:
    required: true
    type: string
  cache-modules:
    required: false
    type: boolean
  install:
    required: false
    type: boolean

outputs:
  node-version:
    value: ${{ steps.node-version.outputs.node-version }}

runs:
  using: composite

  steps:
    - name: Cache Node Modules
      if: inputs.cache-modules
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          packages/fuselage-ui-kit/node_modules
          packages/tools/node_modules
          packages/web-ui-registration/node_modules
          packages/livechat/node_modules
          packages/gazzodown/node_modules
          apps/meteor/ee/server/services/node_modules
          apps/meteor/node_modules
          apps/meteor/packages/meteor-jalik-ufs/.npm/package/node_modules
          apps/meteor/packages/rocketchat-livechat/.npm/plugin/Livechat/node_modules
          ee/packages/presence/node_modules
          ee/packages/omnichannel-services/node_modules
          ee/packages/pdf-worker/node_modules
          ee/apps/omnichannel-transcript/node_modules
          ee/apps/account-service/node_modules
          ee/apps/ddp-streamer/node_modules
          ee/apps/queue-worker/node_modules
        key: node-modules-${{ hashFiles('yarn.lock') }}

    - name: Use Node.js ${{ inputs.node-version }}
      id: node-version
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' && 'yarn' || '' }}

    - name: yarn install
      if: inputs.install && steps.cache-node-modules.outputs.cache-hit != 'true'
      # if: inputs.install
      shell: bash
      run: yarn
