name: Code Checks

on:
  workflow_call:
    inputs:
      TOOL_NODE_FLAGS:
        default: '--max_old_space_size=4096'
        required: false
        type: string

env:
  CI: true
  TOOL_NODE_FLAGS: ${{ inputs.TOOL_NODE_FLAGS }}

jobs:
  code-check:
    runs-on: ubuntu-20.04

    name: ${{ matrix.check == 'ts' && 'TypeScript' || 'Code Lint' }}

    strategy:
      fail-fast: false
      matrix:
        check: ['ts', 'lint']

    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 4

      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: ./.github/actions/setup-node

      - name: Free disk space
        run: |
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h

      - name: Versions
        run: |
          npm --versions
          yarn -v
          node -v
          git version

      - name: yarn install
        run: yarn

      - uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: TS typecheck
        if: matrix.check == 'ts'
        run: yarn turbo run typecheck

      - name: Lint
        if: matrix.check == 'lint'
        run: yarn lint
