name: Tests Unit

on:
  workflow_call:
    inputs:
      mongodb-version:
        default: "['4.4', '6.0']"
        required: false
        type: string

env:
  CI: true
  MONGO_URL: mongodb://localhost:27017/rocketchat?replicaSet=rs0&directConnection=true
  MONGO_OPLOG_URL: mongodb://mongodb:27017/local?replicaSet=rs0&directConnection=true
  TOOL_NODE_FLAGS: --max_old_space_size=4096

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        mongodb-version: ${{ fromJSON(inputs.mongodb-version) }}

    name: MongoDB ${{ matrix.mongodb-version }}

    steps:
      - name: Launch MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: rs0

      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: ./.github/actions/setup-node

      - name: yarn install
        run: yarn

      - uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Unit Test
        run: yarn testunit
